# Generated by Django 3.1.4 on 2021-01-19 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер сертификата')),
                ('url', models.URLField(max_length=255, verbose_name='Ссылка на серимфикат')),
                ('nominal', models.IntegerField(verbose_name='Номинал')),
                ('user1', models.CharField(max_length=30, verbose_name='1 user')),
                ('user2', models.CharField(max_length=30, verbose_name='2 user')),
                ('user3', models.CharField(max_length=30, verbose_name='3 user')),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField(unique=True)),
                ('username', models.CharField(max_length=50, verbose_name='username')),
                ('full_name', models.CharField(default=None, max_length=50, verbose_name='full name')),
                ('phone', models.CharField(max_length=50, verbose_name='phone')),
                ('emale', models.EmailField(blank=True, max_length=50, verbose_name='email_field')),
                ('balance', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='balance')),
                ('language_code', models.CharField(max_length=10, verbose_name='language code')),
                ('date_joined', models.DateTimeField(verbose_name='date joined')),
                ('certificate_quantity', models.IntegerField(primary_key=0, verbose_name='certificate quantity')),
            ],
        ),
    ]
