# Generated by Django 3.1.7 on 2021-04-23 04:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_page', '0003_auto_20210423_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField(blank=True, default=None, unique=True)),
                ('username', models.CharField(blank=True, max_length=50, verbose_name='username')),
                ('full_name', models.CharField(default=None, max_length=50, verbose_name='full name')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='phone')),
                ('email', models.EmailField(max_length=50, verbose_name='email_field')),
                ('balance', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='balance')),
                ('language_code', models.CharField(default='en', max_length=10, verbose_name='language code')),
                ('date_joined', models.DateTimeField(default=datetime.datetime(2021, 4, 23, 11, 2, 13, 586148), verbose_name='date joined')),
                ('certificate_quantity', models.IntegerField(default=0, verbose_name='certificate quantity')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='number',
            field=models.DecimalField(decimal_places=0, default='2304211102587154', max_digits=20, verbose_name='Номер сертификата'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 23, 11, 2, 13, 587154), null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='url',
            field=models.URLField(default='https://mocerts.com/certificate/2304211102587154', max_length=255, verbose_name='Ссылка на серимфикат'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='user1',
            field=models.CharField(default='Мария Рожкова', max_length=30, verbose_name='1 user'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='user1_id',
            field=models.IntegerField(default=6273415),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='user2',
            field=models.CharField(default='Евгения Кулагина', max_length=30, verbose_name='2 user'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='user2_id',
            field=models.IntegerField(default=1781539),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='user3',
            field=models.CharField(default='Георгий Шаров', max_length=30, verbose_name='3 user'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='user3_id',
            field=models.IntegerField(default=6869572),
        ),
    ]
