# Generated by Django 3.1.7 on 2021-04-27 01:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210427_0813'),
        ('main_page', '0010_auto_20210424_1326'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.AddField(
            model_name='account',
            name='cert_1',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='blog.certificate_1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='balance'),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 8, 13, 47, 42060), verbose_name='date joined'),
        ),
    ]
