# Generated by Django 3.1.7 on 2021-05-02 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210502_2356'),
        ('main_page', '0011_auto_20210425_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cert_1',
            field=models.ManyToManyField(blank=True, to='blog.Certificate_1'),
        ),
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('val1', 'Мужской'), ('val2', 'Женский'), ('val3', 'Другой')], default='val3', max_length=12),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='balance'),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 23, 56, 25, 28666), verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='account',
            name='telegram_id',
            field=models.IntegerField(blank=True, default=499859, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
