# Generated by Django 3.1.7 on 2021-04-27 01:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0011_auto_20210427_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 8, 13, 57, 388066), verbose_name='date joined'),
        ),
    ]
