# Generated by Django 3.1.7 on 2021-04-27 01:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210427_0820'),
        ('main_page', '0012_auto_20210427_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cert_1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.certificate_1'),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 8, 20, 56, 628281), verbose_name='date joined'),
        ),
    ]
