# Generated by Django 3.1.7 on 2021-05-04 02:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0012_auto_20210502_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 4, 9, 24, 23, 884035), verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='account',
            name='telegram_id',
            field=models.IntegerField(blank=True, default=965933, null=True),
        ),
    ]
