# Generated by Django 3.1.7 on 2021-04-29 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0013_auto_20210427_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 29, 17, 9, 20, 519966), verbose_name='date joined'),
        ),
    ]
