# Generated by Django 3.1.7 on 2021-05-04 02:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0013_auto_20210504_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 4, 9, 25, 6, 409734), verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='account',
            name='telegram_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
