# Generated by Django 3.1.7 on 2021-04-29 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210429_1715'),
        ('main_page', '0014_auto_20210429_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='cert_1',
        ),
        migrations.AddField(
            model_name='account',
            name='cert_1',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Certificate_1'),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 29, 17, 15, 2, 165961), verbose_name='date joined'),
        ),
    ]
