# Generated by Django 3.1.7 on 2021-05-04 02:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0016_auto_20210504_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 4, 9, 29, 22, 889730), verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(blank=True, choices=[('val1', 'Мужской'), ('val2', 'Женский'), ('val3', 'Другой')], default=None, max_length=12, null=True, verbose_name='Пол'),
        ),
    ]
