# Generated by Django 3.1.7 on 2021-05-04 02:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0017_auto_20210504_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 4, 9, 34, 38, 876725), verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=50, null=True, verbose_name='email_field'),
        ),
    ]
