# Generated by Django 3.1.4 on 2021-01-18 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.IntegerField(unique=True)),
                ('telegram_id', models.IntegerField(unique=True)),
                ('username', models.CharField(max_length=50, verbose_name='username')),
                ('first_name', models.CharField(max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last name')),
                ('phone', models.CharField(max_length=50, verbose_name='phone')),
                ('emale', models.EmailField(blank=True, max_length=50, verbose_name='email_field')),
                ('balance', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='balance')),
                ('language_code', models.CharField(max_length=10, verbose_name='language code')),
                ('date_joined', models.DateTimeField(verbose_name='date joined')),
                ('certificate_quantity', models.IntegerField(primary_key=0, verbose_name='certificate quantity')),
            ],
        ),
    ]
