# Generated by Django 3.1.7 on 2021-04-27 01:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20210119_0646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.DecimalField(decimal_places=0, default='2704210813040060', max_digits=20, verbose_name='Номер сертификата')),
                ('url', models.URLField(default='https://mocerts.com/certificate/2704210813040060', max_length=255, verbose_name='Ссылка на серимфикат')),
                ('nominal', models.IntegerField(default=1, verbose_name='Номинал')),
                ('user1', models.CharField(default='Николай Сальников', max_length=30, verbose_name='1 user')),
                ('user1_id', models.IntegerField(default=5240204)),
                ('user2', models.CharField(default='Вячеслав Моисеев', max_length=30, verbose_name='2 user')),
                ('user2_id', models.IntegerField(default=6754137)),
                ('user3', models.CharField(default='Владимир Иванов', max_length=30, verbose_name='3 user')),
                ('user3_id', models.IntegerField(default=3605629)),
                ('published_date', models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 27, 8, 13, 47, 40060), null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец Сертификата')),
            ],
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
