# Generated by Django 3.1.7 on 2021-04-29 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210427_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate_1',
            name='status',
            field=models.CharField(blank=True, choices=[('val1', 'Отправлен'), ('val2', 'Получен'), ('val3', 'Оплачен'), ('val4', 'Неотправлен')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='certificate_1',
            name='number',
            field=models.DecimalField(decimal_places=0, default='2904211709516967', max_digits=20, verbose_name='Номер сертификата'),
        ),
        migrations.AlterField(
            model_name='certificate_1',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 29, 17, 9, 20, 516967), null=True),
        ),
        migrations.AlterField(
            model_name='certificate_1',
            name='url',
            field=models.URLField(default='https://mocerts.com/certificate/2904211709516967', max_length=255, verbose_name='Ссылка на серимфикат'),
        ),
        migrations.AlterField(
            model_name='certificate_1',
            name='user1',
            field=models.CharField(default='Алиса Андреева', max_length=30, verbose_name='1 user'),
        ),
        migrations.AlterField(
            model_name='certificate_1',
            name='user1_id',
            field=models.IntegerField(default=3716124),
        ),
        migrations.AlterField(
            model_name='certificate_1',
            name='user2',
            field=models.CharField(default='Алина Потапова', max_length=30, verbose_name='2 user'),
        ),
        migrations.AlterField(
            model_name='certificate_1',
            name='user2_id',
            field=models.IntegerField(default=68572),
        ),
        migrations.AlterField(
            model_name='certificate_1',
            name='user3',
            field=models.CharField(default='Мария Косарева', max_length=30, verbose_name='3 user'),
        ),
        migrations.AlterField(
            model_name='certificate_1',
            name='user3_id',
            field=models.IntegerField(default=7386365),
        ),
    ]
