# Generated by Django 3.1.7 on 2021-05-04 02:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210504_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate_1',
            name='number',
            field=models.DecimalField(decimal_places=0, default='0405210925387743', max_digits=20, verbose_name='Номер сертификата'),
        ),
        migrations.AlterField(
            model_name='certificate_1',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 4, 9, 25, 6, 387743), null=True),
        ),
        migrations.AlterField(
            model_name='certificate_1',
            name='url',
            field=models.URLField(default='https://mocerts.com/certificate/0405210925387743', max_length=255, verbose_name='Ссылка на серимфикат'),
        ),
        migrations.AlterField(
            model_name='certificate_1',
            name='user1',
            field=models.CharField(default='Вероника Русакова', max_length=30, verbose_name='1 user'),
        ),
        migrations.AlterField(
            model_name='certificate_1',
            name='user1_id',
            field=models.IntegerField(default=6472652),
        ),
        migrations.AlterField(
            model_name='certificate_1',
            name='user2',
            field=models.CharField(default='Алиса Рудакова', max_length=30, verbose_name='2 user'),
        ),
        migrations.AlterField(
            model_name='certificate_1',
            name='user2_id',
            field=models.IntegerField(default=1659342),
        ),
        migrations.AlterField(
            model_name='certificate_1',
            name='user3',
            field=models.CharField(default='Георгий Бондарев', max_length=30, verbose_name='3 user'),
        ),
        migrations.AlterField(
            model_name='certificate_1',
            name='user3_id',
            field=models.IntegerField(default=4734460),
        ),
    ]
